# Generated by Django 5.2.17 on 2026-09-24 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "E-mail"), ("SMS", "SMS")],
                        max_length=10,
                        verbose_name="Canal",
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Essais"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expire le")),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Vérifié le"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Utilisé le"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Code de réinitialisation",
                "verbose_name_plural": "Codes de réinitialisation",
                "db_table": "reinitialisation_mot_de_passe",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="reinitialis_user_id_cfb38d_idx",
                    )
                ],
            },
        ),
    ]
