# Generated by Django 5.2.17 on 2026-09-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwordresetcode",
            name="channel",
        ),
    ]
