# Generated by Django 5.0.7 on 2026-06-30 08:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("APPLICATION", "Application"),
                            ("INTERVIEW", "Interview"),
                            ("JOB", "Job"),
                            ("SYSTEM", "System"),
                            ("PROFILE", "Profile"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("lu", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "date_envoi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'envoi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notification",
                "ordering": ["-date_envoi"],
            },
        ),
    ]
