# Generated by Django 5.2.17 on 2026-09-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("APPLICATION", "Candidature"),
                    ("INTERVIEW", "Entretien"),
                    ("JOB", "Offre"),
                    ("SYSTEM", "Système"),
                    ("PROFILE", "Profil"),
                ],
                default="SYSTEM",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
