# Generated by Django 5.0.7 on 2026-06-30 08:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score_global",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Score global",
                    ),
                ),
                (
                    "points_forts",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Points forts"
                    ),
                ),
                (
                    "points_faibles",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Points faibles"
                    ),
                ),
                (
                    "conseils",
                    models.JSONField(blank=True, default=list, verbose_name="Conseils"),
                ),
                (
                    "date_feedback",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date du feedback"
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback IA",
                "verbose_name_plural": "Feedbacks IA",
                "db_table": "feedback_ia",
                "ordering": ["-date_feedback"],
            },
        ),
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                (
                    "type_question",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("MULTIPLE_CHOICE", "Multiple Choice"),
                            ("CODE", "Code"),
                            ("BEHAVIORAL", "Behavioral"),
                        ],
                        default="OPEN",
                        max_length=50,
                        verbose_name="Type de question",
                    ),
                ),
                (
                    "reponse",
                    models.TextField(blank=True, null=True, verbose_name="Réponse"),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Score",
                    ),
                ),
                ("ordre", models.IntegerField(verbose_name="Ordre")),
            ],
            options={
                "verbose_name": "Question d'entretien",
                "verbose_name_plural": "Questions d'entretien",
                "db_table": "question_entretien",
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_session",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de session"
                    ),
                ),
                (
                    "type_entretien",
                    models.CharField(
                        choices=[
                            ("TECHNICAL", "Technical"),
                            ("BEHAVIORAL", "Behavioral"),
                            ("MIXED", "Mixed"),
                            ("HR", "HR"),
                        ],
                        default="MIXED",
                        max_length=20,
                        verbose_name="Type d'entretien",
                    ),
                ),
                (
                    "duree",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Durée (minutes)"
                    ),
                ),
                (
                    "score_global",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Score global",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Session d'entretien",
                "verbose_name_plural": "Sessions d'entretien",
                "db_table": "session_entretien",
                "ordering": ["-date_session"],
            },
        ),
    ]
