# Generated by Django 5.0.7 on 2026-06-30 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interviews", "0001_initial"),
        ("jobs", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to="users.candidateprofile",
            ),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="offre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interviews",
                to="jobs.job",
            ),
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="session",
            field=models.ForeignKey(
                db_column="idx_question_session_entretien_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="interviews.interviewsession",
            ),
        ),
        migrations.AddField(
            model_name="aifeedback",
            name="session",
            field=models.OneToOneField(
                db_column="idx_question_session_entretien_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="interviews.interviewsession",
            ),
        ),
        migrations.AddConstraint(
            model_name="aifeedback",
            constraint=models.UniqueConstraint(
                fields=("session",), name="unique_feedback"
            ),
        ),
    ]
