# Generated by Django 5.2.17 on 2026-09-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0003_question_evaluation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewquestion",
            name="type_question",
            field=models.CharField(
                choices=[
                    ("OPEN", "Ouverte"),
                    ("MULTIPLE_CHOICE", "Choix multiple"),
                    ("CODE", "Code"),
                    ("BEHAVIORAL", "Comportementale"),
                ],
                default="OPEN",
                max_length=50,
                verbose_name="Type de question",
            ),
        ),
        migrations.AlterField(
            model_name="interviewsession",
            name="statut",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Planifiée"),
                    ("IN_PROGRESS", "En cours"),
                    ("COMPLETED", "Terminée"),
                    ("CANCELLED", "Annulée"),
                    ("FAILED", "Échouée"),
                ],
                default="SCHEDULED",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="interviewsession",
            name="type_entretien",
            field=models.CharField(
                choices=[
                    ("TECHNICAL", "Technique"),
                    ("BEHAVIORAL", "Comportemental"),
                    ("MIXED", "Mixte"),
                    ("HR", "RH"),
                ],
                default="MIXED",
                max_length=20,
                verbose_name="Type d'entretien",
            ),
        ),
    ]
