# Generated by Django 5.0.7 on 2026-06-30 08:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_candidature",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de candidature"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("REJECTED", "Rejected"),
                            ("HIRED", "Hired"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, null=True, verbose_name="Commentaire"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Candidature",
                "verbose_name_plural": "Candidatures",
                "db_table": "candidature",
                "ordering": ["-date_candidature"],
            },
        ),
        migrations.CreateModel(
            name="CoverLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contenu", models.TextField(verbose_name="Contenu")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "generated_by_ai",
                    models.BooleanField(default=False, verbose_name="Généré par IA"),
                ),
            ],
            options={
                "verbose_name": "Lettre de motivation",
                "verbose_name_plural": "Lettres de motivation",
                "db_table": "lettre_motivation",
                "ordering": ["-date_creation"],
            },
        ),
    ]
