# Generated by Django 5.0.7 on 2026-06-30 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        ("jobs", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="users.candidateprofile",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="offre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="jobs.job",
            ),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="candidature",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cover_letter",
                to="applications.application",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["-date_candidature"], name="candidature_date_ca_f4187f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["statut"], name="candidature_statut_0de775_idx"),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("candidate", "offre"), name="unique_application"
            ),
        ),
        migrations.AddConstraint(
            model_name="coverletter",
            constraint=models.UniqueConstraint(
                fields=("candidature",), name="unique_cover_letter"
            ),
        ),
    ]
