# Generated by Django 5.2.17 on 2026-09-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="statut",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("UNDER_REVIEW", "En cours d'examen"),
                    ("SHORTLISTED", "Présélectionnée"),
                    ("REJECTED", "Refusée"),
                    ("HIRED", "Retenue"),
                    ("WITHDRAWN", "Retirée"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
