# Generated by Django 5.2.17 on 2026-09-24 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_libelles_francais"),
        ("cv_analysis", "0005_cv_stockage_prive"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="cv_analysis.cv",
                verbose_name="CV transmis",
            ),
        ),
    ]
