# Generated by Django 5.0.7 on 2026-06-30 08:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "localisation",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Localisation",
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("CDI", "CDI"),
                            ("CDD", "CDD"),
                            ("FREELANCE", "Freelance"),
                            ("INTERNSHIP", "Internship"),
                            ("APPRENTICESHIP", "Apprenticeship"),
                        ],
                        default="CDI",
                        max_length=20,
                        verbose_name="Type de contrat",
                    ),
                ),
                (
                    "salaire_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Salaire minimum",
                    ),
                ),
                (
                    "salaire_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Salaire maximum",
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="XAF", max_length=10, verbose_name="Devise"
                    ),
                ),
                (
                    "experience_requise",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Expérience requise"
                    ),
                ),
                (
                    "niveau_etude",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Niveau d'étude",
                    ),
                ),
                (
                    "date_publication",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("CLOSED", "Closed"),
                            ("ARCHIVED", "Archived"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre d'emploi",
                "verbose_name_plural": "Offres d'emploi",
                "db_table": "offre_emploi",
                "ordering": ["-date_publication"],
                "indexes": [
                    models.Index(
                        fields=["-date_publication"],
                        name="offre_emplo_date_pu_3e3222_idx",
                    ),
                    models.Index(
                        fields=["statut"], name="offre_emplo_statut_d16fd8_idx"
                    ),
                    models.Index(
                        fields=["type_contrat"], name="offre_emplo_type_co_4bb4ac_idx"
                    ),
                ],
            },
        ),
    ]
