# Generated by Django 5.2.17 on 2026-09-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        ("users", "0004_sync_user_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="competences_requises",
            field=models.ManyToManyField(
                blank=True,
                related_name="offres",
                to="users.skill",
                verbose_name="Compétences requises",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="exigences",
            field=models.TextField(
                blank=True, null=True, verbose_name="Exigences du poste"
            ),
        ),
    ]
