# Generated by Django 5.2.17 on 2026-09-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_exigences_competences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="statut",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("PUBLISHED", "Publiée"),
                    ("CLOSED", "Clôturée"),
                    ("ARCHIVED", "Archivée"),
                    ("EXPIRED", "Expirée"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="type_contrat",
            field=models.CharField(
                choices=[
                    ("CDI", "CDI"),
                    ("CDD", "CDD"),
                    ("FREELANCE", "Freelance"),
                    ("INTERNSHIP", "Stage"),
                    ("APPRENTICESHIP", "Alternance"),
                ],
                default="CDI",
                max_length=20,
                verbose_name="Type de contrat",
            ),
        ),
    ]
