# Generated by Django 5.2.17 on 2026-09-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_libelles_francais"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="lettre_motivation",
            field=models.CharField(
                choices=[
                    ("NON_DEMANDEE", "Non demandée"),
                    ("FACULTATIVE", "Facultative"),
                    ("OBLIGATOIRE", "Obligatoire"),
                ],
                default="FACULTATIVE",
                max_length=20,
                verbose_name="Lettre de motivation",
            ),
        ),
    ]
