# Generated by Django 5.2.17 on 2026-09-26 10:33

from django.db import migrations, models


def classer_stages_existants(apps, schema_editor):
    """Les offres déjà publiées avec le contrat « Stage » deviennent des offres de type Stage."""
    Job = apps.get_model("jobs", "Job")
    Job.objects.filter(type_contrat="INTERNSHIP").update(categorie="STAGE")


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_pieces_candidature"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="categorie",
            field=models.CharField(
                choices=[("EMPLOI", "Emploi"), ("STAGE", "Stage")],
                db_index=True,
                default="EMPLOI",
                max_length=10,
                verbose_name="Type d'offre",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="duree_stage_mois",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Durée du stage (mois)"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="stage_remunere",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Stage rémunéré"
            ),
        ),
        migrations.RunPython(classer_stages_existants, migrations.RunPython.noop),
    ]
