# Generated by Django 5.2.17 on 2026-09-23 19:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0002_job_exigences_competences"),
        ("users", "0004_sync_user_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        verbose_name="Score de compatibilité"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Détail du calcul"
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(auto_now=True, verbose_name="Calculé le"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_results",
                        to="users.candidateprofile",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_results",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat de matching",
                "verbose_name_plural": "Résultats de matching",
                "db_table": "resultat_matching",
                "ordering": ["-score"],
                "indexes": [
                    models.Index(
                        fields=["job", "-score"], name="resultat_ma_job_id_6c5a44_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidate", "job"), name="unique_match_result"
                    )
                ],
            },
        ),
    ]
