# Generated by Django 5.0.7 on 2026-06-30 08:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nom_entreprise",
                    models.CharField(
                        max_length=255, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "secteur",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Secteur"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "site_web",
                    models.TextField(blank=True, null=True, verbose_name="Site web"),
                ),
                (
                    "adresse",
                    models.TextField(blank=True, null=True, verbose_name="Adresse"),
                ),
                (
                    "ville",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ville"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "logo",
                    models.TextField(blank=True, null=True, verbose_name="Logo URL"),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Entreprise",
                "verbose_name_plural": "Entreprises",
                "db_table": "entreprise",
                "ordering": ["-created_at"],
            },
        ),
    ]
