# Generated by Django 5.2.17 on 2026-09-24 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def approve_already_verified(apps, schema_editor):
    """Les entreprises déjà marquées « verified » sont considérées comme validées ; les autres attendent."""
    Company = apps.get_model("companies", "Company")
    Company.objects.filter(verified=True).update(statut_verification="APPROVED")


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="motif_rejet",
            field=models.TextField(
                blank=True, default="", verbose_name="Motif du rejet"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="registre_commerce",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Numéro de registre de commerce (RCCM)",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="statut_verification",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente de vérification"),
                    ("APPROVED", "Validée"),
                    ("REJECTED", "Rejetée"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
                verbose_name="Statut de vérification",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="verifie_le",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Vérifiée le"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="verifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vérifiée par",
            ),
        ),
        migrations.RunPython(approve_already_verified, migrations.RunPython.noop),
    ]
