# Generated by Django 5.2.17 on 2026-09-24 13:46

import common.storage
import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_verification_entreprise"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="document_rccm",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=common.storage.PrivateMediaStorage(),
                upload_to=companies.models.rccm_upload_path,
                verbose_name="Certificat RCCM (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="document_rccm_nom",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Nom d'origine du certificat",
            ),
        ),
    ]
