# Generated by Django 5.0.7 on 2026-06-30 08:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(db_column="mot_de_passe", max_length=128, verbose_name="password")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "date_inscription",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'inscription",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("CANDIDATE", "Candidate"),
                            ("COMPANY", "Company"),
                        ],
                        default="CANDIDATE",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        error_messages={"unique": "Ce username existe déjà."},
                        help_text="Username (optionnel)",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="Membre du personnel"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False, verbose_name="Super utilisateur"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière connexion"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'inscription",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="utilisateur_set",
                        related_query_name="utilisateur",
                        to="auth.group",
                        verbose_name="Groupes",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="utilisateur_set",
                        related_query_name="utilisateur",
                        to="auth.permission",
                        verbose_name="Permissions utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "db_table": "utilisateur",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_naissance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Genre"
                    ),
                ),
                (
                    "adresse",
                    models.TextField(blank=True, null=True, verbose_name="Adresse"),
                ),
                (
                    "ville",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ville"
                    ),
                ),
                (
                    "photo",
                    models.TextField(blank=True, null=True, verbose_name="Photo"),
                ),
                (
                    "biographie",
                    models.TextField(blank=True, null=True, verbose_name="Biographie"),
                ),
                (
                    "linkedin",
                    models.TextField(blank=True, null=True, verbose_name="LinkedIn"),
                ),
                (
                    "github",
                    models.TextField(blank=True, null=True, verbose_name="GitHub"),
                ),
                (
                    "portfolio",
                    models.TextField(blank=True, null=True, verbose_name="Portfolio"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chercheur d'emploi",
                "verbose_name_plural": "Chercheurs d'emploi",
                "db_table": "chercheur_emploi",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="candidateprofile",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_candidate_user"
            ),
        ),
    ]
