# Generated by Django 5.0.7 on 2026-06-30 19:51

from django.db import migrations, models


def rename_password_column_if_needed(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name = 'utilisateur' AND column_name IN ('password', 'mot_de_passe')"
        )
        columns = {row[0] for row in cursor.fetchall()}

    if "password" in columns and "mot_de_passe" not in columns:
        schema_editor.execute(
            'ALTER TABLE "utilisateur" RENAME COLUMN "password" TO "mot_de_passe"'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(rename_password_column_if_needed, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="user",
                    name="password",
                    field=models.CharField(db_column="mot_de_passe", max_length=128),
                ),
            ],
        ),
    ]
