# Generated by Django 5.2.17 on 2026-09-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_sync_user_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("CANDIDATE", "Candidat"),
                    ("COMPANY", "Entreprise"),
                ],
                default="CANDIDATE",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
