# Generated by Django 5.2.17 on 2026-09-28 21:41

from django.db import migrations, models


def comptes_existants(apps, schema_editor):
    # Tout compte existant a déjà ouvert au moins une session (l'inscription connecte
    # automatiquement) : sa prochaine connexion affichera « Bon retour », pas la bienvenue.
    User = apps.get_model("users", "User")
    User.objects.update(nombre_connexions=1)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_libelles_francais"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nombre_connexions",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre de connexions"
            ),
        ),
        migrations.RunPython(comptes_existants, migrations.RunPython.noop),
    ]
