# Generated by Django 5.0.7 on 2026-06-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("priority", models.CharField(default="medium", max_length=20)),
            ],
            options={
                "verbose_name": "AI Recommendation",
                "verbose_name_plural": "AI Recommendations",
                "db_table": "ai_recommendations",
                "ordering": ["priority", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to="cvs/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.IntegerField()),
                ("file_type", models.CharField(max_length=50)),
                ("extracted_text", models.TextField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CV",
                "verbose_name_plural": "CVs",
                "db_table": "cvs",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CVAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("employability_score", models.IntegerField(default=0)),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("weaknesses", models.JSONField(blank=True, default=list)),
                ("recommendations_data", models.JSONField(blank=True, default=list)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CV Analysis",
                "verbose_name_plural": "CV Analyses",
                "db_table": "cv_analyses",
                "ordering": ["-analyzed_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectedSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "proficiency_level",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("years_experience", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Detected Skill",
                "verbose_name_plural": "Detected Skills",
                "db_table": "detected_skills",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MissingSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("importance", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Missing Skill",
                "verbose_name_plural": "Missing Skills",
                "db_table": "missing_skills",
                "ordering": ["name"],
            },
        ),
    ]
