# Generated by Django 5.0.7 on 2026-06-30 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cv_analysis", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cvs",
                to="users.candidateprofile",
            ),
        ),
        migrations.AddField(
            model_name="cvanalysis",
            name="cv",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="cv_analysis.cv",
            ),
        ),
        migrations.AddField(
            model_name="airecommendation",
            name="analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="cv_analysis.cvanalysis",
            ),
        ),
        migrations.AddField(
            model_name="detectedskill",
            name="analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detected_skills",
                to="cv_analysis.cvanalysis",
            ),
        ),
        migrations.AddField(
            model_name="missingskill",
            name="analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missing_skills",
                to="cv_analysis.cvanalysis",
            ),
        ),
    ]
