# Generated by Django 5.2.17 on 2026-09-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_analysis", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvanalysis",
            name="education_level",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cvanalysis",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="cvanalysis",
            name="experience_years",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cvanalysis",
            name="score_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="cvanalysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="COMPLETED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cvanalysis",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
