# Generated by Django 5.2.17 on 2026-09-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_analysis", "0003_analysis_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvanalysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("PROCESSING", "En cours"),
                    ("COMPLETED", "Terminée"),
                    ("FAILED", "Échec"),
                ],
                default="COMPLETED",
                max_length=20,
            ),
        ),
    ]
