# Generated by Django 5.2.17 on 2026-09-24 15:37

import os
import uuid

import common.storage
import cv_analysis.models
from django.conf import settings
from django.core.files import File
from django.core.files.storage import FileSystemStorage
from django.db import migrations, models


def move_cvs_to_private_storage(apps, schema_editor):
    """Les CV étaient servis publiquement sous /media/cvs/<nom d'origine> : on les déplace
    dans le stockage privé sous un nom aléatoire, puis on supprime la copie publique."""
    CV = apps.get_model("cv_analysis", "CV")
    public = FileSystemStorage(location=settings.MEDIA_ROOT)
    private = common.storage.private_storage
    for cv in CV.objects.exclude(file=""):
        old_name = cv.file.name
        if not old_name or not public.exists(old_name):
            continue
        extension = os.path.splitext(old_name)[1].lower()[:10]
        with public.open(old_name, "rb") as handle:
            new_name = private.save(f"cvs/{uuid.uuid4().hex}{extension}", File(handle))
        CV.objects.filter(pk=cv.pk).update(file=new_name)
        public.delete(old_name)


class Migration(migrations.Migration):

    dependencies = [
        ("cv_analysis", "0004_libelles_francais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="file",
            field=models.FileField(
                max_length=255,
                storage=common.storage.PrivateMediaStorage(),
                upload_to=cv_analysis.models.cv_upload_path,
            ),
        ),
        migrations.RunPython(move_cvs_to_private_storage, migrations.RunPython.noop),
    ]
